package telraam.database.jdbc;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;

public class JDBCAbstractDAO {

    private Connection connection;

    JDBCAbstractDAO(Connection connection) {
        this.connection = connection;
    }

    /**
     * Helper method to make a prepared method
     */
    PreparedStatement prepare(String sql) throws SQLException {
        return connection.prepareStatement(sql);
    }

    /**
     * Helper method to make a prepared statement with 'autogenerated keys'
     */
    PreparedStatement prepareAutoGenerated(String sql) throws SQLException {
        return connection.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
    }
}
