template: Hello, %s!

defaultName: ${DW_DEFAULT_NAME:-Stranger}

beaconPort: 4564

database:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:telraam_test

logging:

  # The default level of all loggers. Can be OFF, ERROR, WARN, INFO, DEBUG, TRACE, or ALL.
  level: DEBUG

  appenders:
    - type: console
      threshold: INFO
      target: stderr
